# Generated by publish-homebrew.yaml in L337-org/docker-mcp, from
# scripts/docker-mcp-server.rb.tpl there. Do not edit by hand: a release regenerates this file
# from the template and overwrites it.
#
# This channel is PAUSED, so nothing is currently regenerating it and the version below is stale.
# See the tap README for the reason and for the supported install channels.
class DockerMcpServer < Formula
  desc "MCP server for managing Docker via the Docker SDK for Python"
  homepage "https://github.com/L337-org/docker-mcp"
  version "1.9.2"
  license "MIT"

  depends_on "python@3.14"
  depends_on "uv" => :build

  # Keep Homebrew's post-install cleanup phase (stripping symbols, pruning .la files, fixing
  # permissions) out of the virtualenv, so it leaves the Python extension .so files alone.
  #
  # This is only a candidate workaround for the headerpad failure that paused this channel, and
  # an unverified one: skip_clean affects the cleanup phase only. It does not disable the separate
  # keg-relocation step that rewrites dylib IDs via install_name_tool, which is where that failure
  # actually occurs. See the tap README.
  skip_clean "libexec"

  on_macos do
    on_arm do
      url "https://github.com/L337-org/docker-mcp/releases/download/v1.9.2/docker-mcp-server-1.9.2-wheelhouse-macos-arm64.tar.gz"
      sha256 "de27e70457646bbf52d33f2fcf8a7694847330e97b74becf498f70436526c61b"
    end
    on_intel do
      url "https://github.com/L337-org/docker-mcp/releases/download/v1.9.2/docker-mcp-server-1.9.2-wheelhouse-macos-x86_64.tar.gz"
      sha256 "7679ccdae458c68b609d41f4d80977166742bac5c931073a3d5702821eee3345"
    end
  end

  def install
    python3 = Formula["python@3.14"].opt_bin/"python3.14"
    system "uv", "venv", libexec.to_s, "--python", python3.to_s
    system "uv", "pip", "install",
      "--python", (libexec/"bin/python3").to_s,
      "--no-index",
      "--find-links=#{buildpath}",
      "docker-mcp-server==#{version}"
    bin.install_symlink libexec/"bin/docker-mcp-server"
    bin.install_symlink libexec/"bin/docker-mcp"
  end

  test do
    system libexec/"bin/python3", "-c", "import docker_mcp"
  end
end
